version: '2.1'
services:
  ad_mongo:
    image: mongo
    container_name: ad_mongo
    restart: always
    ports:
      - ${AD_MONGO_PORT}:27017
    volumes:
      - ./data/mongo/configdb:/data/configdb
      - ./data/mongo/db:/data/db
      - ./data/mongodb/log:/var/log/mongodb  # 挂载日志目录
    # command: mongod --auth # 如果要设置密码请开启
    #初始化管理员用户名和密码
    environment:
     MONGO_INITDB_ROOT_USERNAME: ${AD_MONGO_USER}
     MONGO_INITDB_ROOT_PASSWORD: ${AD_MONGO_PWD}
     MONGO_INITDB_DATABASE: ${AD_MONGO_DATABASE}
    tty: true

  ad_elasticsearch:
    image: elasticsearch:7.9.3
    container_name: ad_elasticsearch
    restart: always
    environment:
      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
      - "discovery.type=single-node" #以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m" #设置使用jvm内存大小
    volumes:
      - ./data/elasticsearch/data:/usr/share/elasticsearch/data:rw
      - ./data/elasticsearch/logs:/user/share/elasticsearch/logs:rw
      - ./esplugins:/usr/share/elasticsearch/plugins
    ports:
      - ${AD_ES_PORT}:9200

  ad_kibana:
    image: kibana:7.9.3
    container_name: ad_kibana
    links:
      - ad_elasticsearch:elasticsearch #可以用es这个域名访问elasticsearch服务
    depends_on:
      - ad_elasticsearch #kibana在elasticsearch启动之后再启动
    environment:
      - "elasticsearch.hosts=http://elasticsearch:9200" #设置访问elasticsearch的地址
    ports:
      - 5601:5601

  ad_redis:
    image: redis:latest
    container_name: ad_redis
    # 使用配置文件进行启动，可以选择性设置密码requirepass
    command: redis-server /etc/redis/redis.conf
    ports:
      - ${AD_REDIS_PORT}:6379
    volumes:
      - ./data/redis:/data
      - ./data/redis/redis.conf:/etc/redis/redis.conf

  ad_server:
    image: jarrettluo/all-docs:${AD_SERVER_IMAGE_TAG}
    container_name: ad_server
    environment:
      - REDIS_HOST=${AD_REDIS_HOST}
      - REDIS_PORT=${AD_REDIS_PORT}
      - REDIS_USER=${AD_REDIS_USER}
      - REDIS_PWD=${AD_REDIS_PWD}
      - MONGO_HOST=${AD_MONGO_HOST}
      - MONGO_PORT=${AD_MONGO_PORT}
      - MONGO_USER=${AD_MONGO_USER}
      - MONGO_PWD=${AD_MONGO_PWD}
      - ES_HOST=${AD_ES_HOST}
      - ES_PORT=${AD_ES_PORT}
      - ES_USER=${AD_ES_USER}
      - ES_PWD=${AD_ES_PWD}
      - 'TZ="Asia/Shanghai"'
    ports:
      - ${AD_SERVER_PORT}:8082
    healthcheck:
      test: ["CMD", "nc", "-zv", "localhost", "8082"]
      interval: 6s
      timeout: 10s
      retries: 20
    depends_on:
      - ad_mongo
      - ad_redis

  ad_web:
    image: jarrettluo/all-docs-web:${AD_SERVER_IMAGE_TAG}
    container_name: ad_web
    external_links:
      - ad_server:ad-server
    ports:
      - ${AD_WEB_PORT}:80
    depends_on:
      - ad_server